resources:
- repo: self
  fetchDepth: 15
jobs:
- job: Job_Security
  displayName: Security
  condition: succeeded()
  pool:
    name: Hosted VS2017
  steps:
  - template: _securityChecks.yml

- job: Job_BuildImage
  displayName: Build and Test Build Image
  condition: succeeded()
  pool:
    name: OryxLinux
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildBuildImages;]true"
      echo "##vso[task.setvariable variable=TestBuildImages;]true"
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]false"
      echo "##vso[task.setvariable variable=PushBuildImages;]true"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=PushToDockerHub;]false"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
    displayName: 'Set variables'
  - template: _buildParallel.yml

- job: Job_RuntimeImages
  displayName: Build and Test Runtime Images
  condition: succeeded()
  pool:
    name: OryxLinux
  # Building runtime images can take a long time due our PHP images
  timeoutInMinutes: 150
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildBuildImages;]false"
      echo "##vso[task.setvariable variable=TestBuildImages;]false"
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]true"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]true"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushToDockerHub;]false"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
    displayName: 'Set variables'
  - template: _buildParallel.yml

- job: Job_PythonIntegrationTests
  displayName: Run Python Integration Tests
  dependsOn: 
    - Job_BuildImage
    - Job_RuntimeImages
  pool:
    name: OryxLinux
  timeoutInMinutes: 150
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildBuildImages;]false"
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestBuildImages;]false"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestIntegrationCaseFilter;]category=python"
      echo "##vso[task.setvariable variable=TestIntegration;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=PushToDockerHub;]false"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]false"
    displayName: 'Set variables'
  - template: _buildParallel.yml

- job: Job_DotNetCoreIntegrationTests
  displayName: Run DotNetCore Integration Tests
  dependsOn: 
    - Job_BuildImage
    - Job_RuntimeImages
  pool:
    name: OryxLinux
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildBuildImages;]false"
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestBuildImages;]false"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestIntegrationCaseFilter;]category=dotnetcore"
      echo "##vso[task.setvariable variable=TestIntegration;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=PushToDockerHub;]false"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]false"
    displayName: 'Set variables'
  - template: _buildParallel.yml

- job: Job_NodeIntegrationTests
  displayName: Run NodeJs Integration Tests
  dependsOn: 
    - Job_BuildImage
    - Job_RuntimeImages
  pool:
    name: OryxLinux
  timeoutInMinutes: 150
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildBuildImages;]false"
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestBuildImages;]false"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestIntegrationCaseFilter;]category=node"
      echo "##vso[task.setvariable variable=TestIntegration;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=PushToDockerHub;]false"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]false"
    displayName: 'Set variables'
  - template: _buildParallel.yml

- job: Job_PhpIntegrationTests
  displayName: Run Php Integration Tests
  dependsOn: 
    - Job_BuildImage
    - Job_RuntimeImages
  pool:
    name: OryxLinux
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildBuildImages;]false"
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestBuildImages;]false"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestIntegrationCaseFilter;]category=php"
      echo "##vso[task.setvariable variable=TestIntegration;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=PushToDockerHub;]false"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]false"
    displayName: 'Set variables'
  - template: _buildParallel.yml

- job: Job_DbIntegrationTests
  displayName: Run Database Integration Tests
  dependsOn: 
    - Job_BuildImage
    - Job_RuntimeImages
  pool:
    name: OryxLinux
  steps:
  - script: |
      echo "##vso[task.setvariable variable=BuildBuildImages;]false"
      echo "##vso[task.setvariable variable=BuildRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestBuildImages;]false"
      echo "##vso[task.setvariable variable=TestRuntimeImages;]false"
      echo "##vso[task.setvariable variable=TestIntegrationCaseFilter;]category=db"
      echo "##vso[task.setvariable variable=TestIntegration;]true"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
      echo "##vso[task.setvariable variable=PushToDockerHub;]false"
      echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]false"
    displayName: 'Set variables'
  - template: _buildParallel.yml

- job: Job_ENDIntegrationTests
  displayName: End of Integration Tests
  dependsOn: 
    - Job_BuildImage
    - Job_RuntimeImages
    - Job_PythonIntegrationTests
    - Job_PhpIntegrationTests
    - Job_NodeIntegrationTests
    - Job_DotNetCoreIntegrationTests
    - Job_DbIntegrationTests
  pool:
    name: OryxLinux
  steps:
  - task: ms-devlabs.utilitytasks.task-Shellpp.Shell++@0
    displayName: 'End of Integration Tests'
    inputs:
      type: InlineScript
      script: 'echo "Integration tests ended"'